version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app/server
    command: ["node", "index.js"]
